<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>rqt_bag_diagnostics_demo</name>
  <version>0.0.0</version>
  <description>Demo rqt_bag plugin for diagnostics_msgs</description>
  <maintainer email="davidvlu@gmail.com">David V. Lu!!</maintainer>
  <license>BSD</license>

  <exec_depend>diagnostic_msgs</exec_depend>
  <exec_depend>python_qt_binding</exec_depend>
  <exec_depend>rqt_bag</exec_depend>

  <export>
    <build_type>ament_python</build_type>
    <rqt_bag plugin="${prefix}/plugins.xml"/>
  </export>
</package>
